# Generated by Django 5.2.6 on 2025-09-18 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='активированный аккаунт')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='эл. почта')),
                ('activation_code', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='код активации')),
            ],
        ),
    ]
