# Generated by Django 5.2.6 on 2025-09-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.UUIDField(null=True, unique=True, verbose_name='айди')),
                ('source_name', models.CharField(max_length=100, verbose_name='название источника')),
                ('author', models.CharField(max_length=100, verbose_name='автор')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(max_length=500, verbose_name='описание')),
                ('url', models.URLField(unique=True, verbose_name='юрл')),
                ('url_to_image', models.URLField(verbose_name='юрл на картинку')),
                ('content', models.TextField(max_length=500, verbose_name='содержание')),
            ],
        ),
    ]
